insert into provincias (idprovincia, provincia) values (1, 'Alava'); 
insert into provincias (idprovincia, provincia) values (2, 'Albacete');
insert into provincias (idprovincia, provincia) values (3, 'Alicante');
insert into provincias (idprovincia, provincia) values (4, 'Almería');
insert into provincias (idprovincia, provincia) values (5, 'Avila');
insert into provincias (idprovincia, provincia) values (6, 'badajoz');
insert into provincias (idprovincia, provincia) values (7, 'baleares');
insert into provincias (idprovincia, provincia) values (8, 'barcelona');
insert into provincias (idprovincia, provincia) values (9, 'burgos');
insert into provincias (idprovincia, provincia) values (10,'caceres');
insert into provincias (idprovincia, provincia) values (11,'cadiz');
insert into provincias (idprovincia, provincia) values (12,'castellon');
insert into provincias (idprovincia, provincia) values (13,'ciudad real');
insert into provincias (idprovincia, provincia) values (14,'cordoba');
insert into provincias (idprovincia, provincia) values (15,'coruna');
insert into provincias (idprovincia, provincia) values (16,'cuenca');
insert into provincias (idprovincia, provincia) values (17,'gerona');
insert into provincias (idprovincia, provincia) values (18,'granada');
insert into provincias (idprovincia, provincia) values (19,'guadalajara');
insert into provincias (idprovincia, provincia) values (20,'guipuzcoa');
insert into provincias (idprovincia, provincia) values (21,'huelva');
insert into provincias (idprovincia, provincia) values (22,'huesca');
insert into provincias (idprovincia, provincia) values (23,'jaen');
insert into provincias (idprovincia, provincia) values (24,'leon');
insert into provincias (idprovincia, provincia) values (25,'lerida');
insert into provincias (idprovincia, provincia) values (26,'la rioja');
insert into provincias (idprovincia, provincia) values (27,'lugo');
insert into provincias (idprovincia, provincia) values (28,'madrid');
insert into provincias (idprovincia, provincia) values (29,'malaga');
insert into provincias (idprovincia, provincia) values (30,'murcia');
insert into provincias (idprovincia, provincia) values (31,'navarra');
insert into provincias (idprovincia, provincia) values (32,'orense');
insert into provincias (idprovincia, provincia) values (33,'asturias');
insert into provincias (idprovincia, provincia) values (34,'palencia');
insert into provincias (idprovincia, provincia) values (35,'las palmas');
insert into provincias (idprovincia, provincia) values (36,'pontevedra');
insert into provincias (idprovincia, provincia) values (37,'salamanca');
insert into provincias (idprovincia, provincia) values (38,'santa cruz de tenerife');
insert into provincias (idprovincia, provincia) values (39,'cantabria');
insert into provincias (idprovincia, provincia) values (40,'segovia');
insert into provincias (idprovincia, provincia) values (41,'sevilla');
insert into provincias (idprovincia, provincia) values (42,'soria');
insert into provincias (idprovincia, provincia) values (43,'tarragona');
insert into provincias (idprovincia, provincia) values (44,'teruel');
insert into provincias (idprovincia, provincia) values (45,'toledo');
insert into provincias (idprovincia, provincia) values (46,'valencia');
insert into provincias (idprovincia, provincia) values (47,'valladolid');
insert into provincias (idprovincia, provincia) values (48,'vizcaya');
insert into provincias (idprovincia, provincia) values (49,'zamora');
insert into provincias (idprovincia, provincia) values (50,'zaragoza');
insert into provincias (idprovincia, provincia) values (51,'ceuta');
insert into provincias (idprovincia, provincia) values (52,'melilla');